name: Build image

on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - reopened
      - synchronize

jobs:
  build_push_track:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
